// Curated cross-media franchises — the data TMDB/IGDB/MangaDex can't give us
// on their own. There's no API for "Pokémon spans games + anime + manga" or
// "these two dozen sub-collections are all Marvel" — that's franchise
// knowledge, hand-curated here. Each entry stays small and dynamic (a
// handful of search query strings, not exhaustive ID lists) so a franchise
// automatically picks up new announcements as they land in TMDB/IGDB/
// MangaDex, instead of going stale the day after launch — see
// lib/sources/franchise.ts for how these queries get resolved.

export interface FranchiseTheme {
  // "R G B" triplets (0-255, space-separated) — matches the format already
  // used by the CSS custom properties in app/globals.css.
  primary: string;
  secondary: string;
}

export interface FranchiseQueries {
  movie?: string | string[];
  tvShow?: string | string[];
  game?: string | string[];
  manga?: string | string[];
}

export interface FranchiseDef {
  slug: string;
  name: string;
  tagline: string;
  theme: FranchiseTheme;
  queries: FranchiseQueries;
  // Resolved once, live, during authoring (see scripts/resolve-collections
  // in project history / docs) — NOT guessed. When present, movie parts are
  // fetched via TMDB's Collection API (accurate, catches oddly-titled
  // entries like "Solo: A Star Wars Story") instead of plain text search.
  movieCollectionId?: number;
  // Shown in the compact Discover shelf. Everything (100+) shows in "See all".
  featured?: boolean;
}

export const FRANCHISES: FranchiseDef[] = [
  // ---------- Film ----------
  {
    slug: "star-wars",
    movieCollectionId: 10,
    name: "Star Wars",
    tagline: "A galaxy far, far away.",
    theme: { primary: "20 20 24", secondary: "230 190 80" },
    queries: {
      movie: "Star Wars",
      tvShow: ["The Mandalorian", "Andor", "Ahsoka", "The Bad Batch", "Obi-Wan Kenobi"],
      game: ["Star Wars Jedi", "Star Wars Battlefront", "Star Wars Squadrons"],
    },
    featured: true,
  },
  {
    slug: "marvel-cinematic-universe",
    name: "Marvel Cinematic Universe",
    tagline: "Earth's mightiest heroes, one shared universe.",
    theme: { primary: "178 24 30", secondary: "20 20 24" },
    queries: {
      movie: ["Avengers", "Iron Man", "Captain America", "Thor", "Guardians of the Galaxy", "Doctor Strange", "Black Panther", "Ant-Man", "Spider-Man: Homecoming", "Spider-Man: Far From Home", "Spider-Man: No Way Home"],
      tvShow: ["WandaVision", "Loki", "Hawkeye", "Moon Knight", "She-Hulk", "Ms. Marvel", "Secret Invasion"],
    },
    featured: true,
  },
  {
    slug: "harry-potter",
    movieCollectionId: 1241,
    name: "Harry Potter",
    tagline: "The boy who lived.",
    theme: { primary: "116 26 26", secondary: "182 148 76" },
    queries: { movie: ["Harry Potter", "Fantastic Beasts"], game: "Hogwarts Legacy" },
    featured: true,
  },
  {
    slug: "lord-of-the-rings",
    name: "The Lord of the Rings",
    tagline: "One ring to rule them all.",
    theme: { primary: "24 60 40", secondary: "196 164 90" },
    queries: { movie: ["The Lord of the Rings", "The Hobbit"], tvShow: "The Rings of Power", game: "Shadow of Mordor" },
    featured: true,
  },
  {
    slug: "jurassic-park",
    movieCollectionId: 328,
    name: "Jurassic Park",
    tagline: "Life finds a way.",
    theme: { primary: "20 60 30", secondary: "230 60 40" },
    queries: { movie: ["Jurassic Park", "Jurassic World"] },
  },
  {
    slug: "fast-and-furious",
    name: "Fast & Furious",
    tagline: "Ride or die, family always.",
    theme: { primary: "20 20 24", secondary: "230 50 40" },
    queries: { movie: "Fast", game: "Need for Speed" },
  },
  {
    slug: "mission-impossible",
    movieCollectionId: 87359,
    name: "Mission: Impossible",
    tagline: "Your mission, should you choose to accept it.",
    theme: { primary: "18 18 22", secondary: "220 40 40" },
    queries: { movie: "Mission: Impossible" },
  },
  {
    slug: "james-bond",
    movieCollectionId: 645,
    name: "James Bond",
    tagline: "The name's Bond. James Bond.",
    theme: { primary: "12 14 18", secondary: "160 30 40" },
    queries: { movie: "James Bond", game: "GoldenEye" },
  },
  {
    slug: "john-wick",
    movieCollectionId: 404609,
    name: "John Wick",
    tagline: "Whoever comes, whoever it is, I'll kill them.",
    theme: { primary: "16 16 18", secondary: "200 170 90" },
    queries: { movie: "John Wick" },
  },
  {
    slug: "the-matrix",
    movieCollectionId: 2344,
    name: "The Matrix",
    tagline: "There is no spoon.",
    theme: { primary: "8 12 8", secondary: "70 200 90" },
    queries: { movie: "The Matrix" },
  },
  {
    slug: "alien",
    movieCollectionId: 8091,
    name: "Alien",
    tagline: "In space, no one can hear you scream.",
    theme: { primary: "10 12 14", secondary: "150 165 150" },
    queries: { movie: ["Alien", "Aliens", "Prometheus"], game: "Alien: Isolation" },
  },
  {
    slug: "predator",
    movieCollectionId: 399,
    name: "Predator",
    tagline: "If it bleeds, we can kill it.",
    theme: { primary: "16 14 10", secondary: "150 200 60" },
    queries: { movie: "Predator" },
  },
  {
    slug: "terminator",
    movieCollectionId: 528,
    name: "Terminator",
    tagline: "I'll be back.",
    theme: { primary: "14 14 16", secondary: "200 40 30" },
    queries: { movie: "Terminator" },
  },
  {
    slug: "rocky",
    movieCollectionId: 1575,
    name: "Rocky",
    tagline: "It's not about how hard you hit.",
    theme: { primary: "16 16 18", secondary: "220 60 50" },
    queries: { movie: ["Rocky", "Creed"] },
  },
  {
    slug: "toy-story",
    movieCollectionId: 10194,
    name: "Toy Story",
    tagline: "To infinity and beyond.",
    theme: { primary: "40 90 190", secondary: "230 60 40" },
    queries: { movie: "Toy Story", game: "Toy Story" },
    featured: true,
  },
  {
    slug: "shrek",
    movieCollectionId: 2150,
    name: "Shrek",
    tagline: "Better out than in.",
    theme: { primary: "80 130 40", secondary: "230 170 40" },
    queries: { movie: "Shrek" },
  },
  {
    slug: "despicable-me",
    movieCollectionId: 86066,
    name: "Despicable Me",
    tagline: "Minions. Need we say more?",
    theme: { primary: "230 190 30", secondary: "40 40 46" },
    queries: { movie: ["Despicable Me", "Minions"] },
  },
  {
    slug: "how-to-train-your-dragon",
    movieCollectionId: 89137,
    name: "How to Train Your Dragon",
    tagline: "This is Berk.",
    theme: { primary: "20 60 90", secondary: "220 120 40" },
    queries: { movie: "How to Train Your Dragon" },
  },
  {
    slug: "kung-fu-panda",
    movieCollectionId: 77816,
    name: "Kung Fu Panda",
    tagline: "There is no charge for awesomeness.",
    theme: { primary: "210 40 30", secondary: "230 190 60" },
    queries: { movie: "Kung Fu Panda" },
  },
  {
    slug: "the-hunger-games",
    movieCollectionId: 131635,
    name: "The Hunger Games",
    tagline: "May the odds be ever in your favor.",
    theme: { primary: "20 20 24", secondary: "220 90 40" },
    queries: { movie: "The Hunger Games" },
  },
  {
    slug: "twilight",
    name: "Twilight",
    tagline: "Forever has never felt so short.",
    theme: { primary: "18 20 30", secondary: "150 30 40" },
    queries: { movie: "Twilight" },
  },
  {
    slug: "divergent",
    movieCollectionId: 283579,
    name: "Divergent",
    tagline: "One choice can transform you.",
    theme: { primary: "30 34 40", secondary: "60 140 190" },
    queries: { movie: "Divergent" },
  },
  {
    slug: "maze-runner",
    movieCollectionId: 295130,
    name: "Maze Runner",
    tagline: "Remember, run.",
    theme: { primary: "30 26 20", secondary: "200 150 60" },
    queries: { movie: "Maze Runner" },
  },
  {
    slug: "percy-jackson",
    movieCollectionId: 179919,
    name: "Percy Jackson",
    tagline: "The lightning thief.",
    theme: { primary: "20 60 90", secondary: "220 190 90" },
    queries: { movie: "Percy Jackson", tvShow: "Percy Jackson and the Olympians" },
  },
  {
    slug: "chronicles-of-narnia",
    name: "The Chronicles of Narnia",
    tagline: "Once a king or queen of Narnia, always a king or queen.",
    theme: { primary: "20 40 70", secondary: "200 170 90" },
    queries: { movie: "The Chronicles of Narnia" },
  },
  {
    slug: "pirates-of-the-caribbean",
    movieCollectionId: 295,
    name: "Pirates of the Caribbean",
    tagline: "Why is the rum always gone?",
    theme: { primary: "16 30 30", secondary: "200 170 100" },
    queries: { movie: "Pirates of the Caribbean" },
  },
  {
    slug: "indiana-jones",
    movieCollectionId: 84,
    name: "Indiana Jones",
    tagline: "It's not the years, it's the mileage.",
    theme: { primary: "60 40 20", secondary: "220 170 60" },
    queries: { movie: "Indiana Jones" },
  },
  {
    slug: "ghostbusters",
    movieCollectionId: 2980,
    name: "Ghostbusters",
    tagline: "Who you gonna call?",
    theme: { primary: "20 20 24", secondary: "230 200 40" },
    queries: { movie: "Ghostbusters" },
  },
  {
    slug: "men-in-black",
    name: "Men in Black",
    tagline: "Protecting the Earth from the scum of the universe.",
    theme: { primary: "14 14 16", secondary: "60 130 190" },
    queries: { movie: "Men in Black" },
  },
  {
    slug: "planet-of-the-apes",
    name: "Planet of the Apes",
    tagline: "Apes together strong.",
    theme: { primary: "40 34 24", secondary: "150 170 90" },
    queries: { movie: "Planet of the Apes" },
  },
  {
    slug: "monsterverse",
    name: "Godzilla & Kong",
    tagline: "Titans collide.",
    theme: { primary: "20 40 24", secondary: "230 120 30" },
    queries: { movie: ["Godzilla", "Kong: Skull Island"], game: "Godzilla" },
  },
  {
    slug: "cars",
    movieCollectionId: 87118,
    name: "Cars",
    tagline: "Ka-chow.",
    theme: { primary: "200 40 30", secondary: "40 60 190" },
    queries: { movie: "Cars" },
  },
  {
    slug: "frozen",
    movieCollectionId: 386382,
    name: "Frozen",
    tagline: "Let it go.",
    theme: { primary: "60 150 210", secondary: "230 230 240" },
    queries: { movie: "Frozen" },
  },
  {
    slug: "ice-age",
    movieCollectionId: 8354,
    name: "Ice Age",
    tagline: "Chasing that acorn since 2002.",
    theme: { primary: "40 90 150", secondary: "230 230 240" },
    queries: { movie: "Ice Age" },
  },
  {
    slug: "madagascar",
    movieCollectionId: 14740,
    name: "Madagascar",
    tagline: "I like to move it, move it.",
    theme: { primary: "40 150 90", secondary: "230 190 40" },
    queries: { movie: "Madagascar" },
  },
  {
    slug: "avatar",
    movieCollectionId: 87096,
    name: "Avatar",
    tagline: "I see you.",
    theme: { primary: "20 60 90", secondary: "70 210 190" },
    queries: { movie: "Avatar" },
    featured: true,
  },
  {
    slug: "star-trek",
    name: "Star Trek",
    tagline: "To boldly go where no one has gone before.",
    theme: { primary: "14 14 20", secondary: "220 190 40" },
    queries: { movie: "Star Trek", tvShow: ["Star Trek: The Next Generation", "Star Trek: Discovery", "Star Trek: Picard", "Star Trek: Strange New Worlds"], game: "Star Trek Online" },
  },
  {
    slug: "doctor-who",
    name: "Doctor Who",
    tagline: "Allons-y!",
    theme: { primary: "14 20 40", secondary: "60 140 210" },
    queries: { tvShow: "Doctor Who" },
  },
  {
    slug: "transformers",
    movieCollectionId: 8650,
    name: "Transformers",
    tagline: "More than meets the eye.",
    theme: { primary: "20 24 30", secondary: "210 40 30" },
    queries: { movie: "Transformers", game: "Transformers" },
  },
  {
    slug: "spider-man",
    movieCollectionId: 556,
    name: "Spider-Man",
    tagline: "With great power comes great responsibility.",
    theme: { primary: "200 30 30", secondary: "20 30 100" },
    queries: { movie: "Spider-Man", game: "Marvel's Spider-Man" },
    featured: true,
  },
  {
    slug: "x-men",
    movieCollectionId: 748,
    name: "X-Men",
    tagline: "Mutant and proud.",
    theme: { primary: "20 20 24", secondary: "230 190 40" },
    queries: { movie: "X-Men", game: "X-Men" },
  },
  {
    slug: "batman",
    movieCollectionId: 120794,
    name: "Batman",
    tagline: "It's not who I am underneath.",
    theme: { primary: "14 14 16", secondary: "220 190 40" },
    queries: { movie: ["Batman", "The Dark Knight", "The Batman"], game: "Batman: Arkham" },
    featured: true,
  },
  {
    slug: "superman",
    movieCollectionId: 8537,
    name: "Superman",
    tagline: "Truth, justice, and a better tomorrow.",
    theme: { primary: "20 40 110", secondary: "210 40 30" },
    queries: { movie: "Superman" },
  },
  {
    slug: "wonder-woman",
    movieCollectionId: 468552,
    name: "Wonder Woman",
    tagline: "Peace through strength.",
    theme: { primary: "150 20 30", secondary: "220 190 60" },
    queries: { movie: "Wonder Woman" },
  },
  {
    slug: "the-conjuring",
    movieCollectionId: 313086,
    name: "The Conjuring",
    tagline: "Based on a true story.",
    theme: { primary: "16 14 12", secondary: "150 30 30" },
    queries: { movie: ["The Conjuring", "Annabelle", "The Nun"] },
  },
  {
    slug: "halloween",
    name: "Halloween",
    tagline: "The night he came home.",
    theme: { primary: "16 16 16", secondary: "220 110 20" },
    queries: { movie: "Halloween" },
  },
  {
    slug: "saw",
    movieCollectionId: 656,
    name: "Saw",
    tagline: "I want to play a game.",
    theme: { primary: "16 12 12", secondary: "170 20 20" },
    queries: { movie: "Saw" },
  },
  {
    slug: "scream",
    movieCollectionId: 2602,
    name: "Scream",
    tagline: "What's your favorite scary movie?",
    theme: { primary: "16 16 18", secondary: "200 20 20" },
    queries: { movie: "Scream" },
  },
  {
    slug: "final-destination",
    movieCollectionId: 8864,
    name: "Final Destination",
    tagline: "You can't cheat death.",
    theme: { primary: "16 16 18", secondary: "150 30 30" },
    queries: { movie: "Final Destination" },
  },
  {
    slug: "it",
    movieCollectionId: 477962,
    name: "It",
    tagline: "We all float down here.",
    theme: { primary: "16 16 18", secondary: "220 30 30" },
    queries: { movie: "It" },
  },

  // ---------- TV ----------
  {
    slug: "game-of-thrones",
    name: "Game of Thrones",
    tagline: "Winter is coming.",
    theme: { primary: "20 20 24", secondary: "150 30 30" },
    queries: { tvShow: ["Game of Thrones", "House of the Dragon"] },
    featured: true,
  },
  {
    slug: "stranger-things",
    name: "Stranger Things",
    tagline: "Welcome to the Upside Down.",
    theme: { primary: "20 12 16", secondary: "210 30 40" },
    queries: { tvShow: "Stranger Things" },
  },
  {
    slug: "the-walking-dead",
    name: "The Walking Dead",
    tagline: "Fight the dead, fear the living.",
    theme: { primary: "20 20 18", secondary: "150 30 30" },
    queries: { tvShow: "The Walking Dead" },
  },
  {
    slug: "breaking-bad",
    name: "Breaking Bad",
    tagline: "Say my name.",
    theme: { primary: "16 20 16", secondary: "70 190 60" },
    queries: { tvShow: ["Breaking Bad", "Better Call Saul"] },
  },
  {
    slug: "the-boys",
    name: "The Boys",
    tagline: "Diabolical.",
    theme: { primary: "16 16 18", secondary: "220 190 40" },
    queries: { tvShow: "The Boys" },
  },
  {
    slug: "the-witcher-tv",
    name: "The Witcher",
    tagline: "Toss a coin to your Witcher.",
    theme: { primary: "16 16 18", secondary: "210 190 60" },
    queries: { tvShow: "The Witcher" },
  },

  // ---------- Anime / Manga ----------
  {
    slug: "one-piece",
    movieCollectionId: 23456,
    name: "One Piece",
    tagline: "I'm gonna be King of the Pirates!",
    theme: { primary: "200 30 30", secondary: "40 70 190" },
    queries: { manga: "One Piece", tvShow: "One Piece", game: "One Piece" },
    featured: true,
  },
  {
    slug: "naruto",
    movieCollectionId: 23616,
    name: "Naruto",
    tagline: "Believe it.",
    theme: { primary: "230 140 20", secondary: "20 20 24" },
    queries: { manga: "Naruto", tvShow: ["Naruto", "Boruto"], game: "Naruto" },
    featured: true,
  },
  {
    slug: "dragon-ball",
    movieCollectionId: 386410,
    name: "Dragon Ball",
    tagline: "It's over 9000!",
    theme: { primary: "230 150 20", secondary: "40 90 190" },
    queries: { manga: "Dragon Ball", tvShow: ["Dragon Ball Z", "Dragon Ball Super"], game: "Dragon Ball" },
    featured: true,
  },
  {
    slug: "attack-on-titan",
    movieCollectionId: 383987,
    name: "Attack on Titan",
    tagline: "Dedicate your hearts.",
    theme: { primary: "150 24 24", secondary: "40 40 44" },
    queries: { manga: "Attack on Titan", tvShow: "Attack on Titan", game: "Attack on Titan" },
    featured: true,
  },
  {
    slug: "my-hero-academia",
    movieCollectionId: 1189668,
    name: "My Hero Academia",
    tagline: "Plus Ultra!",
    theme: { primary: "20 130 210", secondary: "220 30 30" },
    queries: { manga: "My Hero Academia", tvShow: "My Hero Academia", game: "My Hero" },
  },
  {
    slug: "demon-slayer",
    movieCollectionId: 925155,
    name: "Demon Slayer",
    tagline: "Set your heart ablaze.",
    theme: { primary: "20 60 40", secondary: "20 20 24" },
    queries: { manga: "Demon Slayer", tvShow: "Demon Slayer", game: "Demon Slayer" },
    featured: true,
  },
  {
    slug: "jujutsu-kaisen",
    movieCollectionId: 1529614,
    name: "Jujutsu Kaisen",
    tagline: "Throughout Heaven and Earth, I alone am the honored one.",
    theme: { primary: "20 20 24", secondary: "150 30 150" },
    queries: { manga: "Jujutsu Kaisen", tvShow: "Jujutsu Kaisen", game: "Jujutsu Kaisen" },
  },
  {
    slug: "bleach",
    movieCollectionId: 23497,
    name: "Bleach",
    tagline: "Get Bankai.",
    theme: { primary: "20 20 24", secondary: "60 130 210" },
    queries: { manga: "Bleach", tvShow: "Bleach", game: "Bleach" },
  },
  {
    slug: "death-note",
    name: "Death Note",
    tagline: "I'll take a potato chip... and eat it!",
    theme: { primary: "16 16 18", secondary: "150 20 20" },
    queries: { manga: "Death Note", tvShow: "Death Note" },
  },
  {
    slug: "fullmetal-alchemist",
    movieCollectionId: 140612,
    name: "Fullmetal Alchemist",
    tagline: "Equivalent exchange.",
    theme: { primary: "160 40 20", secondary: "200 170 90" },
    queries: { manga: "Fullmetal Alchemist", tvShow: "Fullmetal Alchemist" },
  },
  {
    slug: "sword-art-online",
    name: "Sword Art Online",
    tagline: "Link start!",
    theme: { primary: "20 20 30", secondary: "60 130 210" },
    queries: { manga: "Sword Art Online", tvShow: "Sword Art Online", game: "Sword Art Online" },
  },
  {
    slug: "fairy-tail",
    movieCollectionId: 524143,
    name: "Fairy Tail",
    tagline: "Nakama forever.",
    theme: { primary: "230 150 30", secondary: "20 20 24" },
    queries: { manga: "Fairy Tail", tvShow: "Fairy Tail" },
  },
  {
    slug: "hunter-x-hunter",
    movieCollectionId: 571270,
    name: "Hunter x Hunter",
    tagline: "Become a Hunter.",
    theme: { primary: "20 130 90", secondary: "20 20 24" },
    queries: { manga: "Hunter x Hunter", tvShow: "Hunter x Hunter" },
  },
  {
    slug: "tokyo-ghoul",
    name: "Tokyo Ghoul",
    tagline: "Kaneki.",
    theme: { primary: "16 16 18", secondary: "150 20 20" },
    queries: { manga: "Tokyo Ghoul", tvShow: "Tokyo Ghoul" },
  },
  {
    slug: "chainsaw-man",
    movieCollectionId: 1544712,
    name: "Chainsaw Man",
    tagline: "A Denji a day keeps the devils away.",
    theme: { primary: "16 16 18", secondary: "220 30 30" },
    queries: { manga: "Chainsaw Man", tvShow: "Chainsaw Man" },
  },
  {
    slug: "spy-x-family",
    name: "Spy x Family",
    tagline: "Operation Strix.",
    theme: { primary: "40 60 130", secondary: "230 190 60" },
    queries: { manga: "Spy x Family", tvShow: "Spy x Family" },
  },
  {
    slug: "one-punch-man",
    name: "One Punch Man",
    tagline: "One punch, done.",
    theme: { primary: "230 190 30", secondary: "200 30 30" },
    queries: { manga: "One Punch Man", tvShow: "One Punch Man" },
  },
  {
    slug: "mob-psycho-100",
    name: "Mob Psycho 100",
    tagline: "100%.",
    theme: { primary: "20 20 24", secondary: "60 190 150" },
    queries: { manga: "Mob Psycho 100", tvShow: "Mob Psycho 100" },
  },
  {
    slug: "black-clover",
    name: "Black Clover",
    tagline: "I'll become the Wizard King.",
    theme: { primary: "16 16 18", secondary: "60 130 210" },
    queries: { manga: "Black Clover", tvShow: "Black Clover" },
  },
  {
    slug: "re-zero",
    movieCollectionId: 689287,
    name: "Re:Zero",
    tagline: "Starting life in another world.",
    theme: { primary: "20 20 30", secondary: "150 20 60" },
    queries: { manga: "Re:Zero", tvShow: "Re:Zero" },
  },
  {
    slug: "tensura",
    movieCollectionId: 1513903,
    name: "That Time I Got Reincarnated as a Slime",
    tagline: "Rimuru knows best.",
    theme: { primary: "60 130 210", secondary: "20 20 24" },
    queries: { manga: "That Time I Got Reincarnated as a Slime", tvShow: "That Time I Got Reincarnated as a Slime" },
  },
  {
    slug: "overlord",
    movieCollectionId: 499270,
    name: "Overlord",
    tagline: "Ainz Ooal Gown.",
    theme: { primary: "16 16 18", secondary: "150 20 20" },
    queries: { manga: "Overlord", tvShow: "Overlord" },
  },
  {
    slug: "the-promised-neverland",
    name: "The Promised Neverland",
    tagline: "Emma's promise.",
    theme: { primary: "20 60 40", secondary: "230 230 220" },
    queries: { manga: "The Promised Neverland", tvShow: "The Promised Neverland" },
  },
  {
    slug: "vinland-saga",
    name: "Vinland Saga",
    tagline: "I have no enemies.",
    theme: { primary: "20 40 60", secondary: "200 170 90" },
    queries: { manga: "Vinland Saga", tvShow: "Vinland Saga" },
  },
  {
    slug: "berserk",
    name: "Berserk",
    tagline: "The Black Swordsman.",
    theme: { primary: "16 16 16", secondary: "150 20 20" },
    queries: { manga: "Berserk", tvShow: "Berserk" },
  },
  {
    slug: "jojo",
    name: "JoJo's Bizarre Adventure",
    tagline: "ORA ORA ORA!",
    theme: { primary: "150 20 150", secondary: "230 190 30" },
    queries: { manga: "JoJo's Bizarre Adventure", tvShow: "JoJo's Bizarre Adventure" },
  },
  {
    slug: "evangelion",
    movieCollectionId: 96850,
    name: "Neon Genesis Evangelion",
    tagline: "Get in the robot, Shinji.",
    theme: { primary: "60 20 90", secondary: "150 200 60" },
    queries: { tvShow: "Neon Genesis Evangelion", movie: "Evangelion" },
  },
  {
    slug: "cowboy-bebop",
    name: "Cowboy Bebop",
    tagline: "See you, space cowboy.",
    theme: { primary: "20 40 60", secondary: "230 150 30" },
    queries: { tvShow: "Cowboy Bebop" },
  },
  {
    slug: "ghost-in-the-shell",
    movieCollectionId: 23026,
    name: "Ghost in the Shell",
    tagline: "A ghost in a machine.",
    theme: { primary: "20 30 40", secondary: "60 190 210" },
    queries: { tvShow: "Ghost in the Shell", movie: "Ghost in the Shell", manga: "Ghost in the Shell" },
  },
  {
    slug: "digimon",
    name: "Digimon",
    tagline: "Digivolve!",
    theme: { primary: "230 150 20", secondary: "40 90 190" },
    queries: { tvShow: "Digimon", game: "Digimon" },
  },
  {
    slug: "yu-gi-oh",
    name: "Yu-Gi-Oh!",
    tagline: "It's time to duel!",
    theme: { primary: "230 150 20", secondary: "150 20 150" },
    queries: { tvShow: "Yu-Gi-Oh", manga: "Yu-Gi-Oh", game: "Yu-Gi-Oh" },
  },
  {
    slug: "inuyasha",
    name: "Inuyasha",
    tagline: "Sit, boy.",
    theme: { primary: "200 30 30", secondary: "230 230 220" },
    queries: { manga: "Inuyasha", tvShow: "Inuyasha" },
  },
  {
    slug: "detective-conan",
    name: "Detective Conan",
    tagline: "One truth prevails.",
    theme: { primary: "20 40 90", secondary: "230 190 40" },
    queries: { manga: "Detective Conan", tvShow: "Detective Conan" },
  },
  {
    slug: "doraemon",
    name: "Doraemon",
    tagline: "A robotic cat from the 22nd century.",
    theme: { primary: "40 130 210", secondary: "230 190 40" },
    queries: { manga: "Doraemon", tvShow: "Doraemon" },
  },
  {
    slug: "gundam",
    name: "Gundam",
    tagline: "Amuro, go!",
    theme: { primary: "20 20 24", secondary: "210 40 30" },
    queries: { tvShow: "Gundam", game: "Gundam" },
  },

  // ---------- Games ----------
  {
    slug: "the-legend-of-zelda",
    name: "The Legend of Zelda",
    tagline: "It's dangerous to go alone.",
    theme: { primary: "20 90 60", secondary: "220 190 90" },
    queries: { game: "The Legend of Zelda" },
    featured: true,
  },
  {
    slug: "super-mario",
    movieCollectionId: 1434561,
    name: "Super Mario",
    tagline: "Here we go!",
    theme: { primary: "210 30 30", secondary: "40 90 190" },
    queries: { game: "Mario", movie: "Super Mario Bros" },
    featured: true,
  },
  {
    slug: "pokemon",
    movieCollectionId: 34055,
    name: "Pokémon",
    tagline: "Gotta catch 'em all.",
    theme: { primary: "230 190 20", secondary: "40 90 190" },
    queries: { game: "Pokémon", tvShow: "Pokémon", manga: "Pokémon", movie: "Pokémon" },
    featured: true,
  },
  {
    slug: "final-fantasy",
    name: "Final Fantasy",
    tagline: "The power of friendship... and summons.",
    theme: { primary: "20 20 30", secondary: "60 190 210" },
    queries: { game: "Final Fantasy", movie: "Final Fantasy" },
    featured: true,
  },
  {
    slug: "the-elder-scrolls",
    name: "The Elder Scrolls",
    tagline: "Fus Ro Dah.",
    theme: { primary: "20 20 24", secondary: "150 20 20" },
    queries: { game: "The Elder Scrolls" },
    featured: true,
  },
  {
    slug: "fallout",
    name: "Fallout",
    tagline: "War never changes.",
    theme: { primary: "20 60 40", secondary: "230 190 60" },
    queries: { game: "Fallout", tvShow: "Fallout" },
  },
  {
    slug: "god-of-war",
    name: "God of War",
    tagline: "Boy.",
    theme: { primary: "20 20 24", secondary: "150 20 20" },
    queries: { game: "God of War" },
  },
  {
    slug: "the-witcher",
    name: "The Witcher",
    tagline: "Toss a coin to your Witcher.",
    theme: { primary: "16 16 18", secondary: "210 190 60" },
    queries: { game: "The Witcher" },
  },
  {
    slug: "resident-evil",
    movieCollectionId: 17255,
    name: "Resident Evil",
    tagline: "Itchy. Tasty.",
    theme: { primary: "16 16 16", secondary: "150 20 20" },
    queries: { game: "Resident Evil", movie: "Resident Evil" },
  },
  {
    slug: "silent-hill",
    movieCollectionId: 64748,
    name: "Silent Hill",
    tagline: "There was a hole here. It's gone now.",
    theme: { primary: "40 40 44", secondary: "150 20 20" },
    queries: { game: "Silent Hill", movie: "Silent Hill" },
  },
  {
    slug: "metal-gear",
    name: "Metal Gear",
    tagline: "Snake? Snake! SNAAAAKE!",
    theme: { primary: "20 60 40", secondary: "230 190 60" },
    queries: { game: "Metal Gear" },
  },
  {
    slug: "halo",
    name: "Halo",
    tagline: "Finish the fight.",
    theme: { primary: "20 60 90", secondary: "230 230 240" },
    queries: { game: "Halo", tvShow: "Halo" },
    featured: true,
  },
  {
    slug: "mass-effect",
    name: "Mass Effect",
    tagline: "I should go.",
    theme: { primary: "20 20 24", secondary: "230 100 20" },
    queries: { game: "Mass Effect" },
  },
  {
    slug: "dark-souls",
    name: "Dark Souls",
    tagline: "You died.",
    theme: { primary: "16 16 16", secondary: "230 190 90" },
    queries: { game: ["Dark Souls", "Elden Ring", "Bloodborne", "Sekiro"] },
  },
  {
    slug: "persona",
    name: "Persona",
    tagline: "Take your heart.",
    theme: { primary: "16 16 16", secondary: "200 30 30" },
    queries: { game: "Persona" },
  },
  {
    slug: "kingdom-hearts",
    name: "Kingdom Hearts",
    tagline: "The heart is the key.",
    theme: { primary: "20 20 40", secondary: "230 190 60" },
    queries: { game: "Kingdom Hearts" },
  },
  {
    slug: "sonic-the-hedgehog",
    movieCollectionId: 720879,
    name: "Sonic the Hedgehog",
    tagline: "Gotta go fast.",
    theme: { primary: "20 90 210", secondary: "230 190 20" },
    queries: { game: "Sonic", movie: "Sonic the Hedgehog" },
  },
  {
    slug: "street-fighter",
    name: "Street Fighter",
    tagline: "Hadouken!",
    theme: { primary: "20 60 130", secondary: "230 190 40" },
    queries: { game: "Street Fighter" },
  },
  {
    slug: "mortal-kombat",
    movieCollectionId: 9818,
    name: "Mortal Kombat",
    tagline: "Finish him!",
    theme: { primary: "16 16 16", secondary: "180 20 20" },
    queries: { game: "Mortal Kombat", movie: "Mortal Kombat" },
  },
  {
    slug: "tekken",
    name: "Tekken",
    tagline: "The King of Iron Fist.",
    theme: { primary: "20 20 24", secondary: "60 130 210" },
    queries: { game: "Tekken" },
  },
  {
    slug: "minecraft",
    movieCollectionId: 1461530,
    name: "Minecraft",
    tagline: "Blocky, but iconic.",
    theme: { primary: "80 130 50", secondary: "150 100 60" },
    queries: { game: "Minecraft", movie: "Minecraft" },
    featured: true,
  },
  {
    slug: "fortnite",
    name: "Fortnite",
    tagline: "Drop in, gear up, win.",
    theme: { primary: "20 20 130", secondary: "230 40 130" },
    queries: { game: "Fortnite" },
  },
  {
    slug: "overwatch",
    name: "Overwatch",
    tagline: "Heroes never die.",
    theme: { primary: "230 150 20", secondary: "20 20 24" },
    queries: { game: "Overwatch" },
  },
  {
    slug: "league-of-legends",
    name: "League of Legends",
    tagline: "Welcome to the Rift.",
    theme: { primary: "20 20 24", secondary: "60 190 210" },
    queries: { game: "League of Legends", tvShow: "Arcane" },
  },
  {
    slug: "world-of-warcraft",
    name: "World of Warcraft",
    tagline: "For the Horde!",
    theme: { primary: "20 20 24", secondary: "230 100 20" },
    queries: { game: "World of Warcraft" },
  },
  {
    slug: "diablo",
    name: "Diablo",
    tagline: "Stay a while and listen.",
    theme: { primary: "16 16 16", secondary: "180 20 20" },
    queries: { game: "Diablo" },
  },
  {
    slug: "starcraft",
    name: "StarCraft",
    tagline: "My life for Aiur!",
    theme: { primary: "20 20 24", secondary: "60 190 60" },
    queries: { game: "StarCraft" },
  },
  {
    slug: "half-life",
    name: "Half-Life",
    tagline: "The right man in the wrong place.",
    theme: { primary: "230 100 20", secondary: "20 20 24" },
    queries: { game: "Half-Life" },
  },
  {
    slug: "portal",
    name: "Portal",
    tagline: "The cake is a lie.",
    theme: { primary: "20 130 90", secondary: "230 130 30" },
    queries: { game: "Portal" },
  },
  {
    slug: "bioshock",
    name: "BioShock",
    tagline: "Would you kindly?",
    theme: { primary: "20 60 60", secondary: "230 190 90" },
    queries: { game: "BioShock" },
  },
  {
    slug: "borderlands",
    name: "Borderlands",
    tagline: "The Vault awaits.",
    theme: { primary: "230 190 20", secondary: "20 20 24" },
    queries: { game: "Borderlands", movie: "Borderlands" },
  },
  {
    slug: "far-cry",
    name: "Far Cry",
    tagline: "Would you kindly climb this tower?",
    theme: { primary: "230 100 20", secondary: "20 20 24" },
    queries: { game: "Far Cry" },
  },
  {
    slug: "assassins-creed",
    name: "Assassin's Creed",
    tagline: "Nothing is true, everything is permitted.",
    theme: { primary: "16 16 16", secondary: "180 20 20" },
    queries: { game: "Assassin's Creed", movie: "Assassin's Creed" },
    featured: true,
  },
  {
    slug: "call-of-duty",
    name: "Call of Duty",
    tagline: "Boots on the ground.",
    theme: { primary: "20 20 24", secondary: "150 130 60" },
    queries: { game: "Call of Duty" },
  },
  {
    slug: "grand-theft-auto",
    name: "Grand Theft Auto",
    tagline: "Welcome to Vice City.",
    theme: { primary: "20 20 24", secondary: "230 40 130" },
    queries: { game: "Grand Theft Auto" },
    featured: true,
  },
  {
    slug: "yakuza",
    name: "Like a Dragon (Yakuza)",
    tagline: "It's a dragon.",
    theme: { primary: "16 16 16", secondary: "230 190 40" },
    queries: { game: ["Yakuza", "Like a Dragon"] },
  },
  {
    slug: "monster-hunter",
    name: "Monster Hunter",
    tagline: "A good hunter is always prepared.",
    theme: { primary: "20 60 40", secondary: "230 150 30" },
    queries: { game: "Monster Hunter", movie: "Monster Hunter" },
  },
  {
    slug: "dead-space",
    name: "Dead Space",
    tagline: "Cut off their limbs.",
    theme: { primary: "16 16 16", secondary: "230 130 20" },
    queries: { game: "Dead Space" },
  },
  {
    slug: "left-4-dead",
    name: "Left 4 Dead",
    tagline: "The Boomer is coming.",
    theme: { primary: "20 20 24", secondary: "150 20 20" },
    queries: { game: "Left 4 Dead" },
  },
  {
    slug: "apex-legends",
    name: "Apex Legends & Titanfall",
    tagline: "Legends never die.",
    theme: { primary: "230 30 30", secondary: "20 20 24" },
    queries: { game: ["Apex Legends", "Titanfall"] },
  },
  {
    slug: "rainbow-six",
    name: "Rainbow Six",
    tagline: "Breach and clear.",
    theme: { primary: "20 20 24", secondary: "230 130 20" },
    queries: { game: "Rainbow Six" },
  },
  {
    slug: "battlefield",
    name: "Battlefield",
    tagline: "All-out warfare.",
    theme: { primary: "20 20 24", secondary: "230 130 20" },
    queries: { game: "Battlefield" },
  },
  {
    slug: "hitman",
    name: "Hitman",
    tagline: "Agent 47.",
    theme: { primary: "20 20 24", secondary: "230 30 30" },
    queries: { game: "Hitman" },
  },
  {
    slug: "deus-ex",
    name: "Deus Ex",
    tagline: "I never asked for this.",
    theme: { primary: "20 20 24", secondary: "230 190 40" },
    queries: { game: "Deus Ex" },
  },
  {
    slug: "dishonored",
    name: "Dishonored",
    tagline: "Revenge solves everything.",
    theme: { primary: "20 20 24", secondary: "150 30 130" },
    queries: { game: "Dishonored" },
  },
  {
    slug: "bayonetta",
    name: "Bayonetta",
    tagline: "Let's dance, boys.",
    theme: { primary: "20 20 24", secondary: "150 30 130" },
    queries: { game: "Bayonetta" },
  },
  {
    slug: "devil-may-cry",
    name: "Devil May Cry",
    tagline: "Jackpot!",
    theme: { primary: "20 20 24", secondary: "150 20 20" },
    queries: { game: "Devil May Cry" },
  },
  {
    slug: "nier",
    name: "NieR",
    tagline: "Glory to mankind.",
    theme: { primary: "230 230 220", secondary: "20 20 24" },
    queries: { game: "NieR" },
  },
  {
    slug: "xenoblade-chronicles",
    name: "Xenoblade Chronicles",
    tagline: "I'm really feeling it!",
    theme: { primary: "20 130 210", secondary: "230 190 60" },
    queries: { game: "Xenoblade Chronicles" },
  },
  {
    slug: "fire-emblem",
    name: "Fire Emblem",
    tagline: "Permadeath is forever.",
    theme: { primary: "20 60 130", secondary: "230 190 40" },
    queries: { game: "Fire Emblem" },
  },
  {
    slug: "animal-crossing",
    name: "Animal Crossing",
    tagline: "See you tomorrow, real talk.",
    theme: { primary: "150 210 130", secondary: "230 190 90" },
    queries: { game: "Animal Crossing" },
  },
  {
    slug: "kirby",
    name: "Kirby",
    tagline: "Poyo!",
    theme: { primary: "230 150 190", secondary: "230 30 30" },
    queries: { game: "Kirby" },
  },
  {
    slug: "metroid",
    name: "Metroid",
    tagline: "Item get!",
    theme: { primary: "230 130 20", secondary: "20 20 24" },
    queries: { game: "Metroid" },
  },
  {
    slug: "donkey-kong",
    name: "Donkey Kong",
    tagline: "It's on like Donkey Kong.",
    theme: { primary: "150 90 40", secondary: "230 30 30" },
    queries: { game: "Donkey Kong" },
  },
  {
    slug: "star-fox",
    name: "Star Fox",
    tagline: "Do a barrel roll!",
    theme: { primary: "20 60 130", secondary: "230 190 40" },
    queries: { game: "Star Fox" },
  },
  {
    slug: "splatoon",
    name: "Splatoon",
    tagline: "Fresh!",
    theme: { primary: "230 190 20", secondary: "150 30 190" },
    queries: { game: "Splatoon" },
  },
  {
    slug: "rayman",
    name: "Rayman",
    tagline: "No limbs, no problem.",
    theme: { primary: "20 130 210", secondary: "230 190 40" },
    queries: { game: "Rayman" },
  },
  {
    slug: "crash-bandicoot",
    name: "Crash Bandicoot",
    tagline: "Whoa!",
    theme: { primary: "230 130 20", secondary: "150 90 40" },
    queries: { game: "Crash Bandicoot" },
  },
  {
    slug: "spyro",
    name: "Spyro",
    tagline: "Gotta light 'em up.",
    theme: { primary: "150 30 190", secondary: "230 190 40" },
    queries: { game: "Spyro" },
  },
  {
    slug: "uncharted",
    movieCollectionId: 1216426,
    name: "Uncharted",
    tagline: "Greatness from small beginnings.",
    theme: { primary: "150 90 40", secondary: "230 190 90" },
    queries: { game: "Uncharted", movie: "Uncharted" },
  },
  {
    slug: "the-last-of-us",
    name: "The Last of Us",
    tagline: "Endure and survive.",
    theme: { primary: "20 20 24", secondary: "150 20 20" },
    queries: { game: "The Last of Us", tvShow: "The Last of Us" },
    featured: true,
  },
  {
    slug: "horizon",
    name: "Horizon",
    tagline: "A world overgrown with machines.",
    theme: { primary: "20 60 40", secondary: "230 130 20" },
    queries: { game: "Horizon" },
  },
  {
    slug: "cyberpunk",
    name: "Cyberpunk",
    tagline: "Wake the f*** up, samurai.",
    theme: { primary: "20 20 24", secondary: "230 220 40" },
    queries: { game: "Cyberpunk 2077", tvShow: "Cyberpunk: Edgerunners" },
  },
  {
    slug: "destiny",
    name: "Destiny",
    tagline: "Become legend.",
    theme: { primary: "20 20 24", secondary: "60 190 210" },
    queries: { game: "Destiny" },
  },
];

export function getFranchise(slug: string): FranchiseDef | undefined {
  return FRANCHISES.find((f) => f.slug === slug);
}
